name: dartlero_example
version: 1.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: An example how to use Dartlero, a model framework for educational purposes.
homepage: http://ondart.me/
environment:
  sdk: '>=1.10.0 <2.0.0'
dependencies:
  dartlero: ^1.0.5
